### ISSUE TITLE
Error: Loading PostCSS Plugin failed: Cannot find module 'postcss-cssnext'

### ISSUE THREAD

**Issue by hjelmeir** [wojtekmaj/react-date-picker#152]
I just added `react-date-picker` to my project and upon yarn start I get these errors that the css files cannot be loaded because it cannot find `postcss-cssnext`.

```
ERROR in ./node_modules/react-date-picker/dist/DatePicker.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./node_modules/react-date-picker/dist/DatePicker.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: Cannot find module 'postcss-cssnext'

(@.../.postcssrc.yml)
    at load (.../node_modules/postcss-load-config/src/plugins.js:21:13)
    at Object.keys.filter.map (.../node_modules/postcss-load-config/src/plugins.js:53:16)
    at Array.map (<anonymous>)
    at plugins (.../node_modules/postcss-load-config/src/plugins.js:52:8)
    at config.load.then (.../node_modules/postcss-load-config/src/index.js:72:18)

ERROR in ./node_modules/react-calendar/dist/Calendar.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./node_modules/react-calendar/dist/Calendar.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: Cannot find module 'postcss-cssnext'

(@....postcssrc.yml)
    at load (...node_modules/postcss-load-config/src/plugins.js:21:13)
    at Object.keys.filter.map (...node_modules/postcss-load-config/src/plugins.js:53:16)
    at Array.map (<anonymous>)
    at plugins (...node_modules/postcss-load-config/src/plugins.js:52:8)
    at config.load.then (...node_modules/postcss-load-config/src/index.js:72:18)
ℹ ｢wdm｣: Failed to compile.
```

So I `yarn add postcss-cssnext` and get the following message:

`warning postcss-cssnext@3.1.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/`

The project compiles after I manually add postcss-cssnext. The package must be missing in your build.

**Comment by wojtekmaj** [comment]
Hi,
react-date-picker does not use postcss-next. It does, however, import CSS file by default, so your bundler is expected to handle it.

I don't know where you got this message from. Maybe there's something in your own config that triggers it?

**Comment by hjelmeir** [comment]
ok, thanks for the response. We can close out as it's just a me issue (I will figure it out)
