### ISSUE TITLE
``<Fit />'s child needed to have its height decreased`` Warning in console

### ISSUE THREAD

**Issue by gnoul4869** [wojtekmaj/react-date-picker#395]
Hi, there. I'm having this warning shown up everytime I toggle the calendar. The value ``334.78125px`` is not final, it changes everytime the page loads.
```

react_devtools_backend.js:2540 
    
  <Fit />'s child needed to have its height decreased to 334.78125px. 
    at Fit (http://localhost:3000/static/js/vendors~main.chunk.js:51889:5)
    at div
    at DatePicker (http://localhost:3000/static/js/vendors~main.chunk.js:22072:5)
    at DateInput (http://localhost:3000/static/js/main.chunk.js:902:5)
    at div
    at div
    at div
    at div
    at div
    at ProfilePage (http://localhost:3000/static/js/main.chunk.js:10718:82)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:340884:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:341086:29)
    at div
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:340515:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:340136:35)
    at App
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:337644:20)

```
Every things work fine but I want to know what caused this warning and what can I do about this. Thanks in advanced!

**Comment by fl4x** [comment]
Guys I am having the same warning, it's annoying, because I can not override the styles of npm
![image](https://user-images.githubusercontent.com/10885321/148259060-5acd79d8-9b45-4812-b456-32c203e7e743.png)

**Comment by wojtekmaj** [comment]
These warnings are not removable by other things than `process.env.NODE_ENV`, however if you really, really want to suppress these warnings, consider updating secondary dependency `react-fit` to `^1.4.0` (side note: this will be the minimum required version of `react-fit` in React-Date-Picker's next release, so if you're reading this in the future, chances are you don't need to do this), and then doing the following:

Create `noop.js`:
```js
export default function noop() {}
```

Modify `webpack.config.js`:
```js
…
  resolve: {
    …
    alias: {
      'tiny-warning': path.resolve('path', 'to', 'your', 'noop.js'),
    },
  },
…
```

This will replace the module responsible for printing these warnings with your custom noop function, effectively disabling said warnings.

**Comment by igorDykhta** [comment]
This issue is still present with `react-fit "^1.5.1".`
Maybe `react-fit` should have a prop to disable useless warnings?
